db_uri: mongodb://mongo/open5gs

logger:
  file:
    path: /open5gs/install/var/log/open5gs/amf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace


amf:
  sbi:
    server:
      - address: 192.168.0.212
        port: 7777
    client:
      nrf:
        - uri: http://192.168.0.210:7777
  ngap:
    server:
      - address: 192.168.0.212  # Where amf expects to receive NGAP messages from gNB
  metrics:
    server:
      - address: 192.168.0.212
        port: 9090
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 1
  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1
          sd: 1
        - sst: 2
          sd: 1
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
    short: Next
  amf_name: open5gs-amf0
  time:
    t3512:
      value: 540    # 9 minutes * 60 = 540 seconds



