db_uri: mongodb://mongo/open5gs

logger:
  file:
    path: /open5gs/install/var/log/open5gs/ausf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace


ausf:
  sbi:
    server:
      - address: 192.168.0.213
        port: 7777
    client:
      nrf:
        - uri: http://192.168.0.210:7777
  metrics:
    server:
      - address: 192.168.0.213
        port: 9090

