db_uri: mongodb://mongo/open5gs

logger:
  file:
    path: /open5gs/install/var/log/open5gs/nrf.log
    level: debug   # fatal|error|warn|info(default)|debug|trace


nrf:
  sbi:
    server:
      - address: 192.168.0.210
        port: 7777
  metrics:
    server:
      - address: 192.168.0.210
        port: 9090
