db_uri: mongodb://mongo/open5gs

logger:
  file:
    path: /open5gs/install/var/log/open5gs/nssf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace


nssf:
  sbi:
    server:
      - address: 192.168.0.218
        port: 7777
    client:
      nrf:
        - uri: http://192.168.0.210:7777
      nsi:
        - uri: http://192.168.0.210:7777
          s_nssai:
            sst: 1
            sd: 000001
        - uri: http://192.168.0.210:7777
          s_nssai:
            sst: 2
            sd: 000001


