db_uri: mongodb://mongo/open5gs

logger:
  file:
    path: /open5gs/install/var/log/open5gs/upf_mec.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

upf:
  pfcp:
    server:
      - address: 192.168.0.113
  gtpu:
    server:
      - address: 192.168.0.113
  session:
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dnn: mec
      dev: ogstun
  metrics:
    server:
      - address: 192.168.0.113
        port: 9090
